### ISSUE TITLE
Heroku上で画像が表示されない

### ISSUE THREAD

**Issue by Akio-m** [ychubachi/collaborative_development#12]
前回のSinatraアプリで画像を表示しようとしましたが、ローカル上ではブラウザに表示できるけれど、Herokuにデプロイすると表示されていませんでした。どうしたら表示できますか？比嘉＠琉球大学
https://github.com/Akio-m/team_sinatra_project

**Comment by ychubachi** [comment]
http://www.sinatrarb.com/intro-ja.html#%E9%9D%99%E7%9A%84%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB(Static%20Files)
