### ISSUE TITLE
家で作り直し、やり直しをしようとした時

### ISSUE THREAD

**Issue by makotomotegi** [ychubachi/collaborative_development#15]
git init　は出来るのですが
git create  ができません
repositoryが作れないというエラーが出ます。
vagrantはちゃんと動いているようです
railsの設定で何回かミスをして、ディレクトリーは何回か消しています。

16745129 茂木真

**Comment by terra-yucco** [comment]
@ychubachi @makotomotegi 
repositoryが作れないというエラーが出るそうですので、
授業でご回答いただいた内容は誤っているように思います。
(hubが入っていないのであれば、unknown optionやhelpが出るかと思いました)
私が推測するに、vagrantの中のディレクトリは何回か消しているけれども、
GitHub上のリポジトリはすでに存在しているので、新規に作れないのではないかと思います。

**Comment by makotomotegi** [comment]
ありがとうございます
茂木真

2016年9月25日日曜日、Yoshihide Chubachinotifications@github.comさんは書きました:
