### ISSUE TITLE
楽天APIのレシピ利用

### ISSUE THREAD

**Issue by akmura** [ychubachi/collaborative_development#19]
トラブルについて、経緯を備忘録として書いておきます
1. 動かない（NameErrorでRecipeがない)
2. バージョンを1.0.0に指定⇒動く
3. bundle update⇒動かなくなる
4. バージョン指定をやめてbundle update⇒動かない
5. NET:HTTPがないようなので、GemFileに’net'を追加し、Ruby側でrequire 'net/http'を行う⇒動くようになった

適当に依存性が疑わしいものを足していったので、細部は特定出来ていませんが、bundle updateしたら動かなくなったので、依存関係があるものが足りていない可能性が現状あります。

**Comment by ychubachi** [comment]
調査ありがとうございます．
次のとおりUpdateしました．

https://github.com/ychubachi/rakuten_enpit_example/commit/97ffb179924e29d2946471a8d5af31930b57d2f4
