### ISSUE TITLE
gitで利用するエディタ設定

### ISSUE THREAD

**Issue by akmura** [ychubachi/collaborative_development#2]
授業で使用するエディタがEmacs/Vim/Nanoとなっていますが、フレームワーク開発特論で競合発生時に、Emacsが自動で立ち上がっていました。
これを任意のものに変更するにはどの設定を変更する必要がありますでしょうか。

現状、git configでのcore.editorはEmacsが指定されていますがこちらを変更すれば良いでしょうか。

**Comment by ychubachi** [comment]
core.editorで大丈夫だと思います．確認して，結果を教えてください．
