### ISSUE TITLE
git mergeでバイナリファイルがコンフリクトした場合

### ISSUE THREAD

**Issue by tomomi-rivers** [ychubachi/collaborative_development#6]
以下を参考に手元で試しました。
https://github.com/githubtraining/zzz_deprecated-feedback/issues/45
http://blog.digital-squad.net/article/151034635.html

git mergeでバイナリファイルがコンフリクトした場合、ファイルはgit merge実行前のままとなります。

以下を実行してコンフリクトが発生したとします。

```
git checkout master
git merge branch_aaa
```

そのままにしたいとき(=masterを採用）は

```
git checkout --ours <binaryfile> #明示的な実行は不要
git add <binaryfile>
git commit
```

branch_aaaのファイルを採用したいときは

```
git checkout --theirs <binaryfile>
git add <binaryfile>
git commit
```

**Comment by terra-yucco** [comment]
@tomomi-rivers :+1:
![LGTM](https://lgtm.in/p/CzGKFixdq)

バイナリファイルにおいて、2つとも正しい情報を含んでいる場合、
oursを更新して採用する形になるんでしょうか。

※ロゴ画像などで、「イベント名修正」「期間修正」が別ブランチで行われた場合は、
その両方を取り込んだ一枚の画像をアップするのが正しそうな気がしました。

**Comment by tomomi-rivers** [comment]
もちろん状況によっては手動で修正が必要だと思うので、
そのときはoursでもtheirsでも適切な方をベースとして更新するのがいいと思います。

**Comment by terra-yucco** [comment]
@tomomi-rivers ありがとうございました！
